# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Fruzsina Agocs
tagline:             'PhD student in cosmology'
description:         ''
url:                 http://fruzsinaagocs.github.io
baseurl:             ''
plugins: [jekyll-paginate]
paginate:            5
paginate_path: "page:num"
twitter_username: "@caianforphysics"
github_username: "fruzsinaagocs"
linkedin_username: "fruzsina-julia-agocs"
# To render maths:
#markdown: kramdown
#kramdown:
#    math_engine: mathjax
include:
    - _static

# About/contact
author:
  name:              Fruzsina J Agocs
  url:               https://fruzsinaagocs.github.io
  email:             fa325@cam.ac.uk

# Custom vars
# version:             1.0.0
